spring:
  datasource:
    url: jdbc:h2:file:./data/customer-db;AUTO_SERVER=true
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
